ALTER TABLE usuario 
ADD COLUMN IF NOT EXISTS descricao TEXT,
ADD COLUMN IF NOT EXISTS tempoAtendimento VARCHAR(100),
ADD COLUMN IF NOT EXISTS publicoAtendido VARCHAR(100),
ADD COLUMN IF NOT EXISTS modalidade VARCHAR(100);

